package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"path"
	"strings"
	"text/template"
	"unicode"
	"unicode/utf8"
)

// Generator generates constructor code
type Generator struct {
	config *GeneratorConfig
	info   *StructInfo
}

// NewGenerator creates a new generator
func NewGenerator(config *GeneratorConfig, info *StructInfo) *Generator {
	return &Generator{
		config: config,
		info:   info,
	}
}

// Generate generates constructor code based on configuration
func (g *Generator) Generate() (string, error) {
	var buf bytes.Buffer

	// Write package declaration
	buf.WriteString(fmt.Sprintf("package %s\n\n", g.info.PackageName))
	if imports := g.importsForGeneratedTypes(); len(imports) > 0 {
		if len(imports) == 1 {
			if imports[0].Name == "" {
				fmt.Fprintf(&buf, "import %q\n\n", imports[0].Path)
			} else {
				fmt.Fprintf(&buf, "import %s %q\n\n", imports[0].Name, imports[0].Path)
			}
		} else {
			buf.WriteString("import (\n")
			for _, imp := range imports {
				if imp.Name == "" {
					fmt.Fprintf(&buf, "\t%q\n", imp.Path)
					continue
				}
				fmt.Fprintf(&buf, "\t%s %q\n", imp.Name, imp.Path)
			}
			buf.WriteString(")\n\n")
		}
	}
	buf.WriteString("// Code generated by constructor. DO NOT EDIT.\n\n")

	fields := g.info.GetFieldsForConstructor()

	// Generate constructors based on types
	for _, constructorType := range g.config.ConstructorTypes {
		switch constructorType {
		case "allArgs":
			code, err := g.generateAllArgsConstructor(fields)
			if err != nil {
				return "", err
			}
			buf.WriteString(code)
			buf.WriteString("\n\n")

		case "builder":
			code, err := g.generateBuilderConstructor(fields)
			if err != nil {
				return "", err
			}
			buf.WriteString(code)
			buf.WriteString("\n\n")

		case "options":
			code, err := g.generateOptionsConstructor(fields)
			if err != nil {
				return "", err
			}
			buf.WriteString(code)
			buf.WriteString("\n\n")

		default:
			return "", fmt.Errorf("unknown constructor type: %s", constructorType)
		}
	}

	// Generate getters if requested
	if g.config.WithGetter {
		getterFields := g.info.GetFieldsForGetter()
		code := g.generateGetters(getterFields)
		buf.WriteString(code)
		buf.WriteString("\n")
	}

	code, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("format generated code: %w", err)
	}
	return string(code), nil
}

func (g *Generator) importsForGeneratedTypes() []ImportInfo {
	fields := append([]FieldInfo{}, g.info.GetFieldsForConstructor()...)
	if g.config.WithGetter {
		fields = append(fields, g.info.GetFieldsForGetter()...)
	}

	imports := make([]ImportInfo, 0, len(g.info.Imports))
	for _, imp := range g.info.Imports {
		if imp.Name == "_" {
			continue
		}
		if imp.Name == "." || importQualifierUsed(fields, importQualifier(imp)) {
			imports = append(imports, imp)
		}
	}
	return imports
}

func importQualifier(imp ImportInfo) string {
	if imp.Name != "" {
		return imp.Name
	}

	qualifier := path.Base(imp.Path)
	if index := strings.LastIndex(qualifier, ".v"); index > 0 && allDigits(qualifier[index+2:]) {
		return qualifier[:index]
	}
	if strings.HasPrefix(qualifier, "v") && allDigits(qualifier[1:]) {
		return path.Base(path.Dir(imp.Path))
	}
	return qualifier
}

func allDigits(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}

func importQualifierUsed(fields []FieldInfo, qualifier string) bool {
	for _, field := range fields {
		expr, err := parser.ParseExpr(field.Type)
		if err != nil {
			continue
		}

		used := false
		ast.Inspect(expr, func(node ast.Node) bool {
			selector, ok := node.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			ident, ok := selector.X.(*ast.Ident)
			if ok && ident.Name == qualifier {
				used = true
				return false
			}
			return true
		})
		if used {
			return true
		}
	}
	return false
}

// generateAllArgsConstructor generates a constructor with all fields as parameters
func (g *Generator) generateAllArgsConstructor(fields []FieldInfo) (string, error) {
	tmpl := `// New{{.StructName}} creates a new {{.StructName}}
func New{{.StructName}}({{.Params}}) {{.ReturnType}} {
	{{.VarDecl}}{{.StructName}}{
		{{.FieldAssignments}}
	}{{.InitCall}}{{if .ReturnValue}}
	return {{.ReturnValue}}{{end}}
}`

	params := []string{}
	assignments := []string{}
	localNames := uniqueFieldNames(fields, func(field FieldInfo) string {
		return toLowerCamelCase(field.Name)
	})

	for _, field := range fields {
		paramName := localNames[field.Name]
		params = append(params, fmt.Sprintf("%s %s", paramName, field.Type))
		assignments = append(assignments, fmt.Sprintf("%s: %s,", field.Name, paramName))
	}

	returnType := "*" + g.info.Name
	varDecl := "return &"
	returnValue := ""

	if g.config.ReturnValue {
		returnType = g.info.Name
		varDecl = "return "
		returnValue = ""
	}

	// Handle init function
	initCall := ""
	if g.config.InitFunc != "" {
		if g.config.ReturnValue {
			varDecl = "v := "
			returnValue = "v"
		} else {
			varDecl = "v := &"
			returnValue = "v"
		}
		initCall = fmt.Sprintf("\n\tv.%s()", g.config.InitFunc)
	} else {
		// No init function, so returnValue stays empty for direct return
		returnValue = ""
	}

	data := map[string]string{
		"StructName":       g.info.Name,
		"Params":           strings.Join(params, ", "),
		"ReturnType":       returnType,
		"VarDecl":          varDecl,
		"FieldAssignments": strings.Join(assignments, "\n\t\t"),
		"InitCall":         initCall,
		"ReturnValue":      returnValue,
	}

	t, err := template.New("allArgs").Parse(tmpl)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// generateBuilderConstructor generates a builder pattern constructor
func (g *Generator) generateBuilderConstructor(fields []FieldInfo) (string, error) {
	var buf bytes.Buffer

	builderName := g.info.Name + "Builder"
	prefix := g.config.SetterPrefix
	if prefix == "" {
		prefix = "" // No prefix by default, methods named after fields
	}

	// Generate builder struct
	localNames := uniqueFieldNames(fields, func(field FieldInfo) string {
		return toLowerCamelCase(field.Name)
	})
	methodNames := uniqueFieldNames(fields, func(field FieldInfo) string {
		return prefix + toUpperCamelCase(field.Name)
	})

	buf.WriteString(fmt.Sprintf("// %s is a builder for %s\n", builderName, g.info.Name))
	buf.WriteString(fmt.Sprintf("type %s struct {\n", builderName))
	for _, field := range fields {
		buf.WriteString(fmt.Sprintf("\t%s %s\n", localNames[field.Name], field.Type))
	}
	buf.WriteString("}\n\n")

	// Generate builder constructor
	buf.WriteString(fmt.Sprintf("// New%s creates a new %s\n", builderName, builderName))
	buf.WriteString(fmt.Sprintf("func New%s() *%s {\n", builderName, builderName))
	buf.WriteString(fmt.Sprintf("\treturn &%s{}\n", builderName))
	buf.WriteString("}\n\n")

	// Generate setter methods
	for _, field := range fields {
		methodName := methodNames[field.Name]
		paramName := localNames[field.Name]
		fieldName := localNames[field.Name]

		buf.WriteString(fmt.Sprintf("// %s sets the %s field\n", methodName, field.Name))
		buf.WriteString(fmt.Sprintf("func (b *%s) %s(%s %s) *%s {\n",
			builderName, methodName, paramName, field.Type, builderName))
		buf.WriteString(fmt.Sprintf("\tb.%s = %s\n", fieldName, paramName))
		buf.WriteString("\treturn b\n")
		buf.WriteString("}\n\n")
	}

	// Generate Build method
	returnType := "*" + g.info.Name
	if g.config.ReturnValue {
		returnType = g.info.Name
	}

	buf.WriteString(fmt.Sprintf("// Build builds the %s\n", g.info.Name))
	buf.WriteString(fmt.Sprintf("func (b *%s) Build() %s {\n", builderName, returnType))

	if g.config.ReturnValue {
		buf.WriteString(fmt.Sprintf("\tv := %s{\n", g.info.Name))
	} else {
		buf.WriteString(fmt.Sprintf("\tv := &%s{\n", g.info.Name))
	}

	for _, field := range fields {
		buf.WriteString(fmt.Sprintf("\t\t%s: b.%s,\n", field.Name, localNames[field.Name]))
	}
	buf.WriteString("\t}\n")

	// Handle init function
	if g.config.InitFunc != "" {
		buf.WriteString(fmt.Sprintf("\tv.%s()\n", g.config.InitFunc))
	}

	buf.WriteString("\treturn v\n")
	buf.WriteString("}\n")

	return buf.String(), nil
}

// generateOptionsConstructor generates a functional options pattern constructor
func (g *Generator) generateOptionsConstructor(fields []FieldInfo) (string, error) {
	var buf bytes.Buffer

	optionType := g.info.Name + "Option"
	returnType := "*" + g.info.Name
	if g.config.ReturnValue {
		returnType = g.info.Name
	}

	// Generate option type
	buf.WriteString(fmt.Sprintf("// %s is a functional option for configuring %s\n", optionType, g.info.Name))
	buf.WriteString(fmt.Sprintf("type %s func(*%s)\n\n", optionType, g.info.Name))

	// Generate option functions
	localNames := uniqueFieldNames(fields, func(field FieldInfo) string {
		return toLowerCamelCase(field.Name)
	})
	optionNames := uniqueFieldNames(fields, func(field FieldInfo) string {
		return "With" + toUpperCamelCase(field.Name)
	})

	for _, field := range fields {
		optionName := optionNames[field.Name]
		paramName := localNames[field.Name]

		buf.WriteString(fmt.Sprintf("// %s sets the %s field\n", optionName, field.Name))
		buf.WriteString(fmt.Sprintf("func %s(%s %s) %s {\n", optionName, paramName, field.Type, optionType))
		buf.WriteString(fmt.Sprintf("\treturn func(s *%s) {\n", g.info.Name))
		buf.WriteString(fmt.Sprintf("\t\ts.%s = %s\n", field.Name, paramName))
		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")
	}

	// Generate constructor with options
	buf.WriteString(fmt.Sprintf("// New%sWithOptions creates a new %s with functional options\n", g.info.Name, g.info.Name))
	buf.WriteString(fmt.Sprintf("func New%sWithOptions(opts ...%s) %s {\n", g.info.Name, optionType, returnType))

	if g.config.ReturnValue {
		buf.WriteString(fmt.Sprintf("\tv := &%s{}\n", g.info.Name))
	} else {
		buf.WriteString(fmt.Sprintf("\tv := &%s{}\n", g.info.Name))
	}

	buf.WriteString("\tfor _, opt := range opts {\n")
	buf.WriteString("\t\topt(v)\n")
	buf.WriteString("\t}\n")

	// Handle init function
	if g.config.InitFunc != "" {
		buf.WriteString(fmt.Sprintf("\tv.%s()\n", g.config.InitFunc))
	}

	if g.config.ReturnValue {
		buf.WriteString("\treturn *v\n")
	} else {
		buf.WriteString("\treturn v\n")
	}
	buf.WriteString("}\n")

	return buf.String(), nil
}

// generateGetters generates getter methods for all fields
func (g *Generator) generateGetters(fields []FieldInfo) string {
	var buf bytes.Buffer
	getterNames := uniqueFieldNames(fields, func(field FieldInfo) string {
		return "Get" + toUpperCamelCase(field.Name)
	})
	receiverName := firstRune(g.info.Name, unicode.ToLower)

	for _, field := range fields {
		if !field.Exported {
			getterName := getterNames[field.Name]

			buf.WriteString(fmt.Sprintf("// %s returns the %s field\n", getterName, field.Name))
			buf.WriteString(fmt.Sprintf("func (%s *%s) %s() %s {\n",
				receiverName, g.info.Name, getterName, field.Type))
			buf.WriteString(fmt.Sprintf("\treturn %s.%s\n", receiverName, field.Name))
			buf.WriteString("}\n\n")
		}
	}

	return buf.String()
}

// toLowerCamelCase converts a string to lowerCamelCase
func toLowerCamelCase(s string) string {
	return changeFirstRune(s, unicode.ToLower)
}

// toUpperCamelCase converts a string to UpperCamelCase
func toUpperCamelCase(s string) string {
	return changeFirstRune(s, unicode.ToUpper)
}

func changeFirstRune(s string, change func(rune) rune) string {
	if s == "" {
		return s
	}

	r, size := utf8.DecodeRuneInString(s)
	if r == utf8.RuneError && size == 1 {
		return s
	}
	return string(change(r)) + s[size:]
}

func firstRune(s string, change func(rune) rune) string {
	if s == "" {
		return s
	}
	r, _ := utf8.DecodeRuneInString(s)
	return string(change(r))
}

func uniqueFieldNames(fields []FieldInfo, base func(FieldInfo) string) map[string]string {
	names := make(map[string]string, len(fields))
	used := make(map[string]struct{}, len(fields))

	for _, field := range fields {
		name := base(field)
		for suffix := 1; ; suffix++ {
			candidate := name
			if suffix > 1 {
				candidate = fmt.Sprintf("%s%d", name, suffix)
			}
			if _, exists := used[candidate]; exists {
				continue
			}
			names[field.Name] = candidate
			used[candidate] = struct{}{}
			break
		}
	}

	return names
}
