package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSameFile(t *testing.T) {
	if !sameFile("./user.go", "user.go") {
		t.Error("equivalent relative paths should match")
	}
	if sameFile("user.go", "user_gen.go") {
		t.Error("different output path should not match")
	}
}

func TestSameFileResolvesSymlinks(t *testing.T) {
	dir := t.TempDir()
	source := filepath.Join(dir, "source.go")
	output := filepath.Join(dir, "output.go")
	if err := os.WriteFile(source, []byte("package test\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(source, output); err != nil {
		t.Skipf("symlinks are unavailable: %v", err)
	}
	if !sameFile(source, output) {
		t.Fatal("a symlink to the source file must be rejected")
	}
}

func TestFindSourceFileReportsTargetParseErrors(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "config.go"), []byte("package test\n\ntype Config struct { value string `constructor:\"unknown\"` }\n"), 0644); err != nil {
		t.Fatal(err)
	}
	t.Chdir(dir)

	_, err := findSourceFile("Config", "")
	if err == nil || !strings.Contains(err.Error(), `unknown option "unknown"`) {
		t.Fatalf("findSourceFile error = %v, want invalid constructor option", err)
	}
}

func TestWriteGeneratedFileReplacesAtomically(t *testing.T) {
	output := filepath.Join(t.TempDir(), "generated.go")
	if err := os.WriteFile(output, []byte("old"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := writeGeneratedFile(output, "new"); err != nil {
		t.Fatalf("writeGeneratedFile failed: %v", err)
	}
	content, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != "new" {
		t.Fatalf("output = %q, want %q", content, "new")
	}
	info, err := os.Stat(output)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0600 {
		t.Fatalf("permissions = %o, want 600", info.Mode().Perm())
	}
}

func TestDefaultOutputFileAvoidsCaseVariantTypeCollisions(t *testing.T) {
	dir := t.TempDir()
	source := filepath.Join(dir, "types.go")
	if err := os.WriteFile(source, []byte("package test\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if got := defaultOutputFile(source, "Foo"); got != filepath.Join(dir, "foo_gen.go") {
		t.Fatalf("first default output = %q", got)
	}
	if err := os.WriteFile(filepath.Join(dir, "foo_gen.go"), []byte("package test\n\n// Code generated by constructor. DO NOT EDIT.\n\nfunc NewFoo() {}\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if got := defaultOutputFile(source, "FOO"); got != filepath.Join(dir, "foo2_gen.go") {
		t.Fatalf("case-variant default output = %q, want foo2_gen.go", got)
	}
	if got := defaultOutputFile(source, "Foo"); got != filepath.Join(dir, "foo_gen.go") {
		t.Fatalf("same-type default output = %q, want foo_gen.go", got)
	}
}

func TestDefaultOutputFileRecognizesGenericConstructor(t *testing.T) {
	dir := t.TempDir()
	source := filepath.Join(dir, "types.go")
	if err := os.WriteFile(source, []byte("package test\n"), 0644); err != nil {
		t.Fatal(err)
	}
	output := filepath.Join(dir, "box_gen.go")
	if err := os.WriteFile(output, []byte("package test\n\n// Code generated by constructor. DO NOT EDIT.\n\nfunc NewBox[T any](value T) *Box[T] { return nil }\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if got := defaultOutputFile(source, "Box"); got != output {
		t.Fatalf("generic constructor output = %q, want %q", got, output)
	}
}

func TestDefaultOutputFileDoesNotMatchSimilarGeneratedNames(t *testing.T) {
	dir := t.TempDir()
	source := filepath.Join(dir, "types.go")
	if err := os.WriteFile(source, []byte("package test\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "box_gen.go"), []byte("package test\n\n// Code generated by constructor. DO NOT EDIT.\n\nfunc NewBoxBuilder() {}\n"), 0644); err != nil {
		t.Fatal(err)
	}
	want := filepath.Join(dir, "box2_gen.go")
	if got := defaultOutputFile(source, "Box"); got != want {
		t.Fatalf("similar constructor output = %q, want %q", got, want)
	}
}

func TestDefaultOutputFileIgnoresMarkerStrings(t *testing.T) {
	dir := t.TempDir()
	source := filepath.Join(dir, "types.go")
	if err := os.WriteFile(source, []byte("package test\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "box_gen.go"), []byte("package test\n\nconst marker = \"// Code generated by constructor. DO NOT EDIT.\"\n\nfunc NewBox() {}\n"), 0644); err != nil {
		t.Fatal(err)
	}
	want := filepath.Join(dir, "box2_gen.go")
	if got := defaultOutputFile(source, "Box"); got != want {
		t.Fatalf("marker string output = %q, want %q", got, want)
	}
}

func TestDefaultOutputFileIgnoresMarkerLookalikeComments(t *testing.T) {
	dir := t.TempDir()
	source := filepath.Join(dir, "types.go")
	if err := os.WriteFile(source, []byte("package test\n"), 0644); err != nil {
		t.Fatal(err)
	}
	content := "package test\n\n// Code generated by constructor. DO NOT EDIT.\n// func NewBox() *Box { return nil }\n\nconst marker = true\n"
	if err := os.WriteFile(filepath.Join(dir, "box_gen.go"), []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	want := filepath.Join(dir, "box2_gen.go")
	if got := defaultOutputFile(source, "Box"); got != want {
		t.Fatalf("comment lookalike output = %q, want %q", got, want)
	}
}
