package options

import "time"

// Code generated by constructor. DO NOT EDIT.

// AppConfigOption is a functional option for configuring AppConfig
type AppConfigOption func(*AppConfig)

// WithAppName sets the appName field
func WithAppName(appName string) AppConfigOption {
	return func(s *AppConfig) {
		s.appName = appName
	}
}

// WithVersion sets the version field
func WithVersion(version string) AppConfigOption {
	return func(s *AppConfig) {
		s.version = version
	}
}

// WithDebug sets the debug field
func WithDebug(debug bool) AppConfigOption {
	return func(s *AppConfig) {
		s.debug = debug
	}
}

// WithTimeout sets the timeout field
func WithTimeout(timeout time.Duration) AppConfigOption {
	return func(s *AppConfig) {
		s.timeout = timeout
	}
}

// WithMaxWorkers sets the maxWorkers field
func WithMaxWorkers(maxWorkers int) AppConfigOption {
	return func(s *AppConfig) {
		s.maxWorkers = maxWorkers
	}
}

// WithCacheDir sets the cacheDir field
func WithCacheDir(cacheDir string) AppConfigOption {
	return func(s *AppConfig) {
		s.cacheDir = cacheDir
	}
}

// NewAppConfigWithOptions creates a new AppConfig with functional options
func NewAppConfigWithOptions(opts ...AppConfigOption) AppConfig {
	v := &AppConfig{}
	for _, opt := range opts {
		opt(v)
	}
	return *v
}
