package options

// Code generated by constructor. DO NOT EDIT.

// ServerOption is a functional option for configuring Server
type ServerOption func(*Server)

// WithAddress sets the address field
func WithAddress(address string) ServerOption {
	return func(s *Server) {
		s.address = address
	}
}

// WithPort sets the port field
func WithPort(port int) ServerOption {
	return func(s *Server) {
		s.port = port
	}
}

// WithTlsKey sets the tlsKey field
func WithTlsKey(tlsKey string) ServerOption {
	return func(s *Server) {
		s.tlsKey = tlsKey
	}
}

// NewServerWithOptions creates a new Server with functional options
func NewServerWithOptions(opts ...ServerOption) *Server {
	v := &Server{}
	for _, opt := range opts {
		opt(v)
	}
	return v
}

// GetAddress returns the address field
func (s *Server) GetAddress() string {
	return s.address
}

// GetPort returns the port field
func (s *Server) GetPort() int {
	return s.port
}

// GetInstanceID returns the instanceID field
func (s *Server) GetInstanceID() string {
	return s.instanceID
}
