package allargs

// Code generated by constructor. DO NOT EDIT.

// NewProduct creates a new Product
func NewProduct(id int, name string, price float64, description string) *Product {
	return &Product{
		id:          id,
		name:        name,
		price:       price,
		description: description,
	}
}

// GetId returns the id field
func (p *Product) GetId() int {
	return p.id
}

// GetName returns the name field
func (p *Product) GetName() string {
	return p.name
}

// GetPrice returns the price field
func (p *Product) GetPrice() float64 {
	return p.price
}
