package allargs

import "time"

// Code generated by constructor. DO NOT EDIT.

// NewUser creates a new User
func NewUser(id int, name string, email string, createdAt time.Time) *User {
	return &User{
		id:        id,
		name:      name,
		email:     email,
		createdAt: createdAt,
	}
}
