package builder

// Code generated by constructor. DO NOT EDIT.

// DatabaseBuilder is a builder for Database
type DatabaseBuilder struct {
	host     string
	port     int
	username string
	password string
}

// NewDatabaseBuilder creates a new DatabaseBuilder
func NewDatabaseBuilder() *DatabaseBuilder {
	return &DatabaseBuilder{}
}

// Host sets the host field
func (b *DatabaseBuilder) Host(host string) *DatabaseBuilder {
	b.host = host
	return b
}

// Port sets the port field
func (b *DatabaseBuilder) Port(port int) *DatabaseBuilder {
	b.port = port
	return b
}

// Username sets the username field
func (b *DatabaseBuilder) Username(username string) *DatabaseBuilder {
	b.username = username
	return b
}

// Password sets the password field
func (b *DatabaseBuilder) Password(password string) *DatabaseBuilder {
	b.password = password
	return b
}

// Build builds the Database
func (b *DatabaseBuilder) Build() *Database {
	v := &Database{
		host:     b.host,
		port:     b.port,
		username: b.username,
		password: b.password,
	}
	return v
}

// GetHost returns the host field
func (d *Database) GetHost() string {
	return d.host
}

// GetPort returns the port field
func (d *Database) GetPort() int {
	return d.port
}

// GetUsername returns the username field
func (d *Database) GetUsername() string {
	return d.username
}

// GetPoolSize returns the poolSize field
func (d *Database) GetPoolSize() int {
	return d.poolSize
}
